const bcrypt = require('bcryptjs');
const mysql = require('mysql2/promise');
const env = require('../src/config/env');
const { pool: dashboardPool } = require('../src/config/db');
const logger = require('../src/observability/logger');
const storage = require('../src/services/documentStorageService');
const { buildPdf } = require('../src/services/invoicePdfService');
const analytics = require('../src/services/dashboardAnalyticsService');
const { connectWithRetry } = require('../src/utils/connectWithRetry');

const PASSWORD = 'DemoPassword!2026';
const EMAIL = { vendor: 'demo.vendor@workday.local', atlasPm: 'demo.pm@workday.local', novaPm: 'demo.pm.nova@workday.local', primary: 'demo.contractor@workday.local', candidate: 'demo.candidate@workday.local' };
const DATE = { activeStart: '2026-07-01', activeEnd: '2026-12-31', historyStart: '2026-04-01', historyEnd: '2026-06-30', upcomingStart: '2026-10-01', invoice: '2026-09-01', futureDue: '2026-10-15', overdue: '2026-09-01' };

function permitted() { return process.env.DEMO_SEED_ENABLED === 'true' && /(_demo|_restore)$/.test(env.db.name); }
async function firstId(c, sql, values) { const [rows] = await c.query(sql, values); if (!rows.length) throw new Error('Expected deterministic demo record was not found.'); return rows[0].id; }
async function ensureUser(c, hash, name, email, role) {
  await c.query(`INSERT INTO users(name,email,password_hash,role,password_set_at) VALUES(?,?,?,?,NOW()) ON DUPLICATE KEY UPDATE name=VALUES(name),password_hash=VALUES(password_hash),role=VALUES(role),password_set_at=NOW()`, [name, email, hash, role]);
  return firstId(c, 'SELECT id FROM users WHERE email=?', [email]);
}
async function ensureClient(c, name, normalized, legacy) {
  let [rows] = await c.query('SELECT id FROM client_companies WHERE normalized_name=?', [normalized]);
  if (!rows.length && legacy) { const [old] = await c.query('SELECT id FROM client_companies WHERE normalized_name=?', [legacy]); if (old.length) { await c.query('UPDATE client_companies SET name=?,normalized_name=? WHERE id=?', [name, normalized, old[0].id]); return old[0].id; } }
  if (!rows.length) { const [result] = await c.query('INSERT INTO client_companies(name,normalized_name) VALUES(?,?)', [name, normalized]); return result.insertId; }
  await c.query('UPDATE client_companies SET name=? WHERE id=?', [name, rows[0].id]); return rows[0].id;
}
async function ensureContractor(c, userId, vendorId, d) {
  await c.query(`INSERT INTO contractors(user_id,vendor_id,hourly_rate,status,skill,headline,total_experience_years,notes) VALUES(?,?,?,?,?,?,?,'Deterministic demo profile.') ON DUPLICATE KEY UPDATE vendor_id=VALUES(vendor_id),status=VALUES(status),skill=VALUES(skill),headline=VALUES(headline),total_experience_years=VALUES(total_experience_years)`, [userId, vendorId, d.cost, d.status || 'ACTIVE', d.skill, d.headline, d.years]);
  return firstId(c, 'SELECT id FROM contractors WHERE user_id=?', [userId]);
}
async function ensureProject(c, pmId, company, d) {
  const [rows] = await c.query('SELECT id FROM projects WHERE pm_id=? AND name=? ORDER BY id LIMIT 1', [pmId, d.name]);
  if (!rows.length) { const [result] = await c.query(`INSERT INTO projects(name,description,company_name,pm_id,start_date,end_date,expected_hours,budget,currency,max_hours_per_day,max_hours_per_week,allow_weekend,backdate_limit_days,candidate_response_sla_hours,status) VALUES(?,?,?,?,?,?,?,?,?,12,50,0,120,24,?)`, [d.name, d.description, company, pmId, d.start, d.end, d.hours, d.budget, 'USD', d.status]); return result.insertId; }
  await c.query(`UPDATE projects SET description=?,company_name=?,start_date=?,end_date=?,expected_hours=?,budget=?,currency='USD',max_hours_per_day=12,max_hours_per_week=50,allow_weekend=0,backdate_limit_days=120,candidate_response_sla_hours=24,status=? WHERE id=?`, [d.description, company, d.start, d.end, d.hours, d.budget, d.status, rows[0].id]); return rows[0].id;
}
async function ensureRequirement(c, projectId, skillId, skill, count, status) {
  await c.query(`INSERT INTO project_requirements(project_id,skill,skill_id,required_count,description,status) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE skill_id=VALUES(skill_id),required_count=VALUES(required_count),description=VALUES(description),status=VALUES(status)`, [projectId, skill, skillId, count, `${skill} delivery capacity`, status]);
  return firstId(c, 'SELECT id FROM project_requirements WHERE project_id=? AND skill=?', [projectId, skill]);
}
async function ensureRate(c, companyId, vendorId, skillId, bill, cost) {
  const [rows] = await c.query(`SELECT id FROM rate_cards WHERE client_company_id=? AND vendor_id=? AND skill_id=? AND status='ACTIVE' AND effective_from<='2026-07-01' AND (effective_to IS NULL OR effective_to>='2026-07-01') ORDER BY effective_from DESC,id DESC LIMIT 1`, [companyId, vendorId, skillId]);
  if (rows.length) return rows[0].id;
  const [result] = await c.query(`INSERT INTO rate_cards(client_company_id,vendor_id,skill_id,effective_from,effective_to,bill_rate,cost_rate,currency,status) VALUES(?,?,?,'2026-01-01',NULL,?,?,'USD','ACTIVE')`, [companyId, vendorId, skillId, bill, cost]); return result.insertId;
}
async function ensureAssignment(c, d) {
  const [rows] = await c.query('SELECT id FROM project_assignments WHERE contractor_id=? AND project_id=? ORDER BY id LIMIT 1', [d.contractor, d.project]); if (rows.length) return rows[0].id;
  const [result] = await c.query(`INSERT INTO project_assignments(contractor_id,project_id,requirement_id,allocated_hours,bill_rate_snapshot,cost_rate_snapshot,currency,rate_card_id,status,released_at,assigned_date,start_date,end_date,planned_last_working_date,actual_end_date,release_reason,released_by) VALUES(?,?,?,?,?,?,'USD',?,?,${d.status === 'RELEASED' ? 'NOW()' : 'NULL'},?,?,?,?,?,?,?)`, [d.contractor, d.project, d.requirement, d.allocated, d.bill, d.cost, d.rateCard, d.status, d.start, d.start, d.end, d.end, d.status === 'RELEASED' ? d.end : null, d.reason || null, d.status === 'RELEASED' ? d.pm : null]); return result.insertId;
}
async function ensureCandidate(c, d) {
  const [rows] = await c.query('SELECT id FROM candidate_submissions WHERE project_id=? AND requirement_id=? AND contractor_id=? AND status=? ORDER BY id LIMIT 1', [d.project, d.requirement, d.contractor, d.status]); if (rows.length) return rows[0].id;
  const reviewed = ['ACCEPTED', 'REJECTED'].includes(d.status);
  const [result] = await c.query(`INSERT INTO candidate_submissions(project_id,requirement_id,contractor_id,vendor_id,proposed_start_date,proposed_end_date,status,submitted_at,reviewed_at,reviewed_by,review_reason) VALUES(?,?,?,?,?,?,?,${d.stale ? 'DATE_SUB(NOW(),INTERVAL 5 DAY)' : 'NOW()'},${reviewed ? 'NOW()' : 'NULL'},?,?)`, [d.project, d.requirement, d.contractor, d.vendor, d.start, d.end, d.status, reviewed ? d.pm : null, d.reason || null]); return result.insertId;
}
async function ensureTimesheet(c, d) {
  const reviewed = ['APPROVED', 'REJECTED'].includes(d.status);
  await c.query(`INSERT INTO timesheets(contractor_id,project_id,work_date,hours_logged,description,status,submitted_at,reviewed_by,reviewed_at,rejection_reason) VALUES(?,?,?,?,?,?,${d.status === 'DRAFT' ? 'NULL' : 'NOW()'},?,${reviewed ? 'NOW()' : 'NULL'},?) ON DUPLICATE KEY UPDATE id=LAST_INSERT_ID(id)`, [d.contractor, d.project, d.date, d.hours, d.description, d.status, reviewed ? d.pm : null, d.status === 'REJECTED' ? 'Please correct the demo entry.' : null]);
}
async function ensureMilestone(c, project, d) {
  const [rows] = await c.query('SELECT id FROM milestones WHERE project_id=? AND name=? ORDER BY id LIMIT 1', [project, d.name]); if (rows.length) return rows[0].id;
  const [result] = await c.query(`INSERT INTO milestones(project_id,name,description,sequence_order,due_date,threshold_hours,status,met_at) VALUES(?,?,?,?,?,?,?,${d.status === 'MET' ? 'NOW()' : 'NULL'})`, [project, d.name, d.description, d.sequence, d.due, d.threshold, d.status]); return result.insertId;
}
async function ensureBilling(c, milestone, contractor, hours, rate) {
  await c.query(`INSERT INTO milestone_billings(milestone_id,contractor_id,approved_hours,hourly_rate,currency,billing_amount) VALUES(?,?,?,?,'USD',?) ON DUPLICATE KEY UPDATE id=LAST_INSERT_ID(id)`, [milestone, contractor, hours, rate, Number((hours * rate).toFixed(2))]);
  return firstId(c, 'SELECT id FROM milestone_billings WHERE milestone_id=? AND contractor_id=?', [milestone, contractor]);
}
async function ensureInvoice(c, d) {
  let rows; if (d.number) [rows] = await c.query('SELECT id FROM invoices WHERE invoice_number=?', [d.number]); else [rows] = await c.query('SELECT i.id FROM invoices i JOIN invoice_items ii ON ii.invoice_id=i.id WHERE ii.milestone_billing_id=? LIMIT 1', [d.billing]);
  if (rows.length) return rows[0].id;
  const submitted = d.status !== 'DRAFT'; const reviewed = ['APPROVED', 'REJECTED'].includes(d.status);
  const [result] = await c.query(`INSERT INTO invoices(invoice_number,milestone_billing_id,project_id,contractor_id,vendor_id,client_company_id,currency,invoice_date,due_date,payment_terms_days,tax_rate,amount,subtotal_amount,tax_amount,adjustment_amount,total_amount,status,generated_at,submitted_at,reviewed_by,reviewed_at,rejection_reason,document_version) VALUES(?,NULL,?,?,?,?,'USD',?,?,30,?,?,?,?,?,?,?,NOW(),${submitted ? 'NOW()' : 'NULL'},?,${reviewed ? 'NOW()' : 'NULL'},?,?)`, [d.number || null, d.project, d.contractor, d.vendor, d.company, DATE.invoice, d.due, d.taxRate, d.subtotal, d.subtotal, d.tax, d.adjustment, d.total, d.status, reviewed ? d.pm : null, d.status === 'REJECTED' ? 'Demo rejection: supporting detail required.' : null, submitted ? 1 : 0]);
  const invoiceId = result.insertId;
  await c.query(`INSERT INTO invoice_items(invoice_id,milestone_billing_id,approved_hours,bill_rate,amount,contractor_name_snapshot,skill_name_snapshot,milestone_name_snapshot,billing_period_label) VALUES(?,?,?,?,?,?,?,?,?)`, [invoiceId, d.billing, d.hours, d.rate, d.subtotal, d.contractorName, d.skillName, d.milestoneName, 'Deterministic demo period']);
  if (d.adjustment) await c.query('INSERT INTO invoice_adjustments(invoice_id,description,amount) VALUES(?,?,?)', [invoiceId, d.adjustmentDescription || 'Demo adjustment', d.adjustment]);
  if (submitted) { const pdf = buildPdf({ invoice_number: d.number, invoice_date: DATE.invoice, due_date: d.due, project_name: d.projectName, currency: 'USD', subtotal_amount: d.subtotal, tax_rate: d.taxRate, tax_amount: d.tax, adjustment_amount: d.adjustment, total_amount: d.total, items: [{ contractor_name_snapshot: d.contractorName, skill_name_snapshot: d.skillName, milestone_name_snapshot: d.milestoneName, approved_hours: d.hours, bill_rate: d.rate, amount: d.subtotal }], adjustments: d.adjustment ? [{ description: d.adjustmentDescription || 'Demo adjustment', amount: d.adjustment }] : [] }); const document = await storage.store({ contentBase64: pdf.toString('base64'), mimeType: 'application/pdf' }); await c.query('UPDATE invoices SET pdf_storage_key=?,pdf_size_bytes=?,pdf_generated_at=NOW(),document_frozen_at=NOW() WHERE id=?', [document.key, document.sizeBytes, invoiceId]); }
  return invoiceId;
}
async function ensurePayment(c, invoice, vendor, amount, reference) { const [rows] = await c.query('SELECT id FROM payments WHERE invoice_id=? AND reference=? LIMIT 1', [invoice, reference]); if (rows.length) return; await c.query(`INSERT INTO payments(invoice_id,amount,currency,paid_at,reference,method,notes,recorded_by) VALUES(?,?,'USD','2026-09-02 10:00:00',?,'BANK_TRANSFER','Deterministic demo settlement',?)`, [invoice, amount, reference, vendor]); }
async function ensureDocument(c, file, contractor, filename, type, status, expiry, vendor) { const [rows] = await c.query('SELECT id FROM contractor_documents WHERE contractor_id=? AND original_filename=? LIMIT 1', [contractor, filename]); if (rows.length) return; const verified = status === 'VERIFIED'; await c.query(`INSERT INTO contractor_documents(contractor_id,document_type,storage_key,original_filename,mime_type,size_bytes,status,expiry_date,verified_by,verified_at,rejection_reason) VALUES(?,?,?,?,'application/pdf',?,?,?, ?,${verified ? 'NOW()' : 'NULL'},?)`, [contractor, type, file.key, filename, file.sizeBytes, status, expiry, verified ? vendor : null, status === 'REJECTED' ? 'Demo document needs replacement.' : null]); }

async function createSummary(c, vendor, clients, atlasProject) {
  const [projectRows] = await c.query(`SELECT p.status,COUNT(DISTINCT p.id) count FROM projects p WHERE EXISTS(SELECT 1 FROM project_assignments pa JOIN contractors co ON co.id=pa.contractor_id WHERE pa.project_id=p.id AND co.vendor_id=?) GROUP BY p.status`, [vendor]);
  const [[contractors]] = await c.query('SELECT COUNT(*) count FROM contractors WHERE vendor_id=?', [vendor]);
  const [[assignments]] = await c.query('SELECT COUNT(*) count FROM project_assignments pa JOIN contractors co ON co.id=pa.contractor_id WHERE co.vendor_id=?', [vendor]);
  const [candidateRows] = await c.query('SELECT status,COUNT(*) count FROM candidate_submissions WHERE vendor_id=? GROUP BY status', [vendor]);
  const [timesheetRows] = await c.query('SELECT t.status,COUNT(*) count FROM timesheets t JOIN contractors co ON co.id=t.contractor_id WHERE co.vendor_id=? GROUP BY t.status', [vendor]);
  const [invoiceRows] = await c.query('SELECT status,COUNT(*) count FROM invoices WHERE vendor_id=? GROUP BY status', [vendor]);
  const [[payments]] = await c.query(`SELECT SUM(paid=0) unpaid_invoices,SUM(paid>0 AND paid<total_amount) partially_paid,SUM(paid=total_amount) fully_paid FROM (SELECT i.id,i.total_amount,COALESCE(SUM(p.amount),0) paid FROM invoices i LEFT JOIN payments p ON p.invoice_id=i.id WHERE i.vendor_id=? AND i.status='APPROVED' GROUP BY i.id,i.total_amount) x`, [vendor]);
  const expected = [];
  for (const [scope, filter] of [['Unfiltered', {}], ['Client A — Atlas Commerce', { clientId: clients.atlas }], ['Client B — Nova Digital', { clientId: clients.nova }], ['ACTIVE projects', { status: 'ACTIVE' }], ['COMPLETED projects', { status: 'COMPLETED' }], ['Atlas Commerce Modernization', { projectId: atlasProject }]]) { const d = await analytics.dashboard('VENDOR', vendor, filter); expected.push({ scope, active_projects: d.financial.active_projects, completed_projects: d.financial.completed_projects, active_contractors: d.workforce.active_contractors, approved_hours: d.time.approved_hours, candidate_submissions: d.candidates.submissions, billable_uninvoiced: d.financial.billable_uninvoiced_amount, submitted_invoices: d.financial.submitted_invoice_amount, approved_invoices: d.financial.approved_invoice_amount, approved_earnings: d.financial.approved_earnings_amount, paid: d.financial.paid_amount, outstanding: d.financial.outstanding_amount, overdue: d.financial.overdue_amount, margin: d.financial.margin?.amount ?? null }); }
  const map = (rows) => Object.fromEntries(rows.map((row) => [row.status, Number(row.count)]));
  return { clients: 2, projects: map(projectRows), contractors: Number(contractors.count), assignments: Number(assignments.count), candidate_submissions: map(candidateRows), timesheets: map(timesheetRows), invoices: map(invoiceRows), payments: Object.fromEntries(Object.entries(payments).map(([key, value]) => [key, Number(value || 0)])), expected_dashboard: expected };
}

async function run() {
  if (!permitted()) throw new Error('Demo seed is disabled. Set DEMO_SEED_ENABLED=true and use an explicit *_demo or *_restore database.');
  const c = await connectWithRetry(() => mysql.createConnection({ host: env.db.host, port: env.db.port, user: env.db.user, password: env.db.password, database: env.db.name }), { attempts: env.startupDbRetries, delayMs: env.startupDbRetryMs, onRetry: ({ attempt, maxAttempts, error }) => logger.warn('demo_seed_database_connection_retry', { attempt, max_attempts: maxAttempts, error_message: error.message }) });
  let expandedBefore = false;
  try {
    const [[marker]] = await c.query("SELECT COUNT(*) count FROM projects WHERE name='Nova Internal Prototype'"); expandedBefore = Number(marker.count) > 0;
    const hash = await bcrypt.hash(PASSWORD, 12); await c.beginTransaction();
    const userDefs = {
      vendor: ['Demo Vendor', EMAIL.vendor, 'VENDOR'], atlasPm: ['Demo PM — Atlas', EMAIL.atlasPm, 'PM'], novaPm: ['Demo PM — Nova', EMAIL.novaPm, 'PM'], primary: ['Demo Contractor', EMAIL.primary, 'CONTRACTOR'], candidate: ['Demo Candidate', EMAIL.candidate, 'CONTRACTOR'],
      atlasFrontend: ['Avery Frontend', 'demo.atlas.frontend@workday.local', 'CONTRACTOR'], atlasQa: ['Quinn QA', 'demo.atlas.qa@workday.local', 'CONTRACTOR'], atlasUpcoming: ['Uma Upcoming', 'demo.atlas.upcoming@workday.local', 'CONTRACTOR'], atlasBackendHistory: ['Harper Backend', 'demo.atlas.backend.history@workday.local', 'CONTRACTOR'], atlasDevops: ['Devon DevOps', 'demo.atlas.devops@workday.local', 'CONTRACTOR'], novaData: ['Dakota Data', 'demo.nova.data@workday.local', 'CONTRACTOR'], novaDevopsHistory: ['Morgan DevOps', 'demo.nova.devops.history@workday.local', 'CONTRACTOR'], novaQaHistory: ['Casey QA', 'demo.nova.qa.history@workday.local', 'CONTRACTOR'], unassigned: ['Riley Available', 'demo.unassigned@workday.local', 'CONTRACTOR'], atlasReview: ['Taylor Review Queue', 'demo.atlas.review@workday.local', 'CONTRACTOR'], novaReview: ['Jordan Review Queue', 'demo.nova.review@workday.local', 'CONTRACTOR'], rejected: ['Reese Rejected', 'demo.rejected@workday.local', 'CONTRACTOR'], withdrawn: ['Skyler Withdrawn', 'demo.withdrawn@workday.local', 'CONTRACTOR']
    };
    const users = {}; for (const [key, value] of Object.entries(userDefs)) users[key] = await ensureUser(c, hash, ...value);
    const clients = { atlas: await ensureClient(c, 'Atlas Commerce', 'atlas commerce', 'demo client company'), nova: await ensureClient(c, 'Nova Digital', 'nova digital') };
    await c.query(`INSERT INTO project_managers(user_id,company_id,department) VALUES(?,?,?) ON DUPLICATE KEY UPDATE company_id=VALUES(company_id),department=VALUES(department)`, [users.atlasPm, clients.atlas, 'Commerce Platforms']); await c.query(`INSERT INTO project_managers(user_id,company_id,department) VALUES(?,?,?) ON DUPLICATE KEY UPDATE company_id=VALUES(company_id),department=VALUES(department)`, [users.novaPm, clients.nova, 'Digital Products']);
    for (const [company, pm] of [[clients.atlas, users.atlasPm], [clients.nova, users.novaPm]]) await c.query(`INSERT INTO client_vendor_relationships(client_company_id,vendor_id,status,invited_by,accepted_at) VALUES(?,?,'ACTIVE',?,NOW()) ON DUPLICATE KEY UPDATE status='ACTIVE',accepted_at=COALESCE(accepted_at,NOW())`, [company, users.vendor, pm]);
    const [skillRows] = await c.query('SELECT id,code FROM skills'); const skills = Object.fromEntries(skillRows.map((row) => [row.code, row.id])); for (const skill of ['FRONTEND','BACKEND','QA','DEVOPS','DATA']) if (!skills[skill]) throw new Error(`Required skill ${skill} is missing.`);
    const contractorDefs = { primary: ['BACKEND',75,'Primary demo backend specialist',6], candidate: ['BACKEND',70,'Reusable E2E candidate',4], atlasFrontend: ['FRONTEND',140,'Atlas frontend lead',8], atlasQa: ['QA',110,'Atlas quality engineer',5], atlasUpcoming: ['QA',105,'Upcoming Atlas test engineer',4], atlasBackendHistory: ['BACKEND',155,'Completed Atlas migration specialist',9,'INACTIVE'], atlasDevops: ['DEVOPS',135,'Atlas platform engineer',7], novaData: ['DATA',150,'Nova analytics engineer',8], novaDevopsHistory: ['DEVOPS',165,'Completed Nova platform engineer',10], novaQaHistory: ['QA',120,'Cancelled-project QA history',6], unassigned: ['QA',100,'Available for a new assignment',3], atlasReview: ['BACKEND',145,'Awaiting Atlas PM review',7], novaReview: ['FRONTEND',130,'Awaiting Nova PM review',6], rejected: ['BACKEND',125,'Rejected candidate example',5], withdrawn: ['FRONTEND',115,'Withdrawn candidate example',4] };
    const contractors = {}; for (const [key, [skill,cost,headline,years,status]] of Object.entries(contractorDefs)) { contractors[key] = await ensureContractor(c, users[key], users.vendor, { skill,cost,headline,years,status }); await c.query(`INSERT INTO contractor_skills(contractor_id,skill_id,proficiency,years_experience,is_primary) VALUES(?,?,'ADVANCED',?,1) ON DUPLICATE KEY UPDATE proficiency=VALUES(proficiency),years_experience=VALUES(years_experience),is_primary=1`, [contractors[key], skills[skill], years]); }
    const projectDefs = {
      demo: ['atlasPm','Atlas Commerce','Demo Platform Upgrade','Primary browser lifecycle demonstration.',DATE.activeStart,DATE.activeEnd,120,18000,'ACTIVE'],
      atlasActive: ['atlasPm','Atlas Commerce','Atlas Commerce Modernization','Modern storefront and service integration.',DATE.activeStart,DATE.activeEnd,240,60000,'ACTIVE'], atlasHold: ['atlasPm','Atlas Commerce','Atlas Mobile Expansion','Mobile delivery paused pending client planning.',DATE.activeStart,DATE.activeEnd,100,26000,'ON_HOLD'], atlasCompleted: ['atlasPm','Atlas Commerce','Atlas Legacy Migration','Completed legacy data migration.',DATE.historyStart,DATE.historyEnd,80,22000,'COMPLETED'], novaActive: ['novaPm','Nova Digital','Nova Analytics Platform','Analytics platform and reporting APIs.','2026-08-01',DATE.activeEnd,160,48000,'ACTIVE'], novaCompleted: ['novaPm','Nova Digital','Nova Customer Portal','Completed customer self-service portal.',DATE.historyStart,DATE.historyEnd,60,18000,'COMPLETED'], novaCancelled: ['novaPm','Nova Digital','Nova Internal Prototype','Cancelled internal prototype retained for history.',DATE.historyStart,'2026-05-15',40,9000,'CANCELLED']
    };
    const projects = {}; for (const [key, [pm,company,name,description,start,end,hours,budget,status]] of Object.entries(projectDefs)) { projects[key] = await ensureProject(c, users[pm], company, {name,description,start,end,hours,budget,status}); await c.query(`INSERT INTO project_vendors(project_id,vendor_id,status) VALUES(?,?,'ACTIVE') ON DUPLICATE KEY UPDATE status='ACTIVE'`, [projects[key], users.vendor]); }
    const reqDefs = { demo:[['BACKEND',2]], atlasActive:[['FRONTEND',1],['QA',2],['BACKEND',1]], atlasHold:[['DEVOPS',1],['QA',1]], atlasCompleted:[['BACKEND',1],['QA',1]], novaActive:[['DATA',1],['FRONTEND',1]], novaCompleted:[['DEVOPS',1],['BACKEND',1]], novaCancelled:[['QA',1],['FRONTEND',1]] };
    const req = {}; for (const [project, values] of Object.entries(reqDefs)) { req[project] = {}; for (const [skill,count] of values) req[project][skill] = await ensureRequirement(c, projects[project], skills[skill], skill, count, ['COMPLETED','CANCELLED'].includes(projectDefs[project][8]) ? 'CLOSED' : 'OPEN'); }
    const rateDefs = { atlas:{FRONTEND:[250,140],QA:[180,110],BACKEND:[250,155],DEVOPS:[210,135]}, nova:{DATA:[225,150],FRONTEND:[215,130],DEVOPS:[250,165],BACKEND:[240,155],QA:[190,120]} }; const rates = {atlas:{},nova:{}}; for (const [client, values] of Object.entries(rateDefs)) for (const [skill,[bill,cost]] of Object.entries(values)) rates[client][skill] = await ensureRate(c, clients[client], users.vendor, skills[skill], bill, cost);
    const assignmentDefs = [ ['atlasFrontend','atlasActive','FRONTEND','atlas',160,250,140,'ACTIVE',DATE.activeStart,DATE.activeEnd], ['atlasQa','atlasActive','QA','atlas',80,180,110,'ACTIVE',DATE.activeStart,DATE.activeEnd], ['atlasUpcoming','atlasActive','QA','atlas',60,180,105,'ACTIVE',DATE.upcomingStart,DATE.activeEnd], ['atlasDevops','atlasHold','DEVOPS','atlas',100,210,135,'ACTIVE',DATE.activeStart,DATE.activeEnd], ['atlasBackendHistory','atlasCompleted','BACKEND','atlas',80,250,155,'RELEASED',DATE.historyStart,DATE.historyEnd,'Completed planned migration work'], ['novaData','novaActive','DATA','nova',120,225,150,'ACTIVE','2026-08-01',DATE.activeEnd], ['novaDevopsHistory','novaCompleted','DEVOPS','nova',60,250,165,'RELEASED',DATE.historyStart,DATE.historyEnd,'Customer portal delivered'], ['novaQaHistory','novaCancelled','QA','nova',40,190,120,'RELEASED',DATE.historyStart,'2026-05-15','Prototype cancelled by client'] ];
    for (const [contractor,project,skill,client,allocated,bill,cost,status,start,end,reason] of assignmentDefs) { await ensureAssignment(c,{contractor:contractors[contractor],project:projects[project],requirement:req[project][skill],allocated,bill,cost,rateCard:rates[client][skill],status,start,end,reason,pm:users[projectDefs[project][0]]}); await ensureCandidate(c,{project:projects[project],requirement:req[project][skill],contractor:contractors[contractor],vendor:users.vendor,status:'ACCEPTED',start,end,pm:users[projectDefs[project][0]],reason:'Accepted for deterministic demo assignment.'}); }
    await ensureCandidate(c,{project:projects.atlasActive,requirement:req.atlasActive.BACKEND,contractor:contractors.atlasReview,vendor:users.vendor,status:'SUBMITTED',start:'2026-09-15',end:DATE.activeEnd,pm:users.atlasPm,stale:true}); await ensureCandidate(c,{project:projects.novaActive,requirement:req.novaActive.FRONTEND,contractor:contractors.novaReview,vendor:users.vendor,status:'SUBMITTED',start:'2026-09-20',end:DATE.activeEnd,pm:users.novaPm}); await ensureCandidate(c,{project:projects.atlasActive,requirement:req.atlasActive.BACKEND,contractor:contractors.rejected,vendor:users.vendor,status:'REJECTED',start:'2026-09-15',end:DATE.activeEnd,pm:users.atlasPm,reason:'Experience mix did not match this requirement.'}); await ensureCandidate(c,{project:projects.novaActive,requirement:req.novaActive.FRONTEND,contractor:contractors.withdrawn,vendor:users.vendor,status:'WITHDRAWN',start:'2026-09-20',end:DATE.activeEnd,pm:users.novaPm,reason:'Candidate became unavailable.'});
    const approved = [...['03','04','05','06','07','10','11','12','13'].map((day)=>[contractors.atlasFrontend,projects.atlasActive,`2026-08-${day}`,8,'Atlas approved frontend delivery','APPROVED',users.atlasPm]), [contractors.atlasQa,projects.atlasActive,'2026-08-14',8,'Atlas approved QA delivery','APPROVED',users.atlasPm], ...['01','02','03','04'].map((day)=>[contractors.novaData,projects.novaActive,`2026-09-${day}`,8,'Nova approved analytics delivery','APPROVED',users.novaPm]), [contractors.atlasBackendHistory,projects.atlasCompleted,'2026-06-10',10,'Atlas migration batch one','APPROVED',users.atlasPm], [contractors.atlasBackendHistory,projects.atlasCompleted,'2026-06-11',10,'Atlas migration batch two','APPROVED',users.atlasPm], [contractors.atlasBackendHistory,projects.atlasCompleted,'2026-06-17',5,'Atlas migration warranty closeout','APPROVED',users.atlasPm], [contractors.novaDevopsHistory,projects.novaCompleted,'2026-06-15',6,'Nova portal deployment','APPROVED',users.novaPm], [contractors.novaDevopsHistory,projects.novaCompleted,'2026-06-16',6,'Nova portal stabilization','APPROVED',users.novaPm], [contractors.atlasDevops,projects.atlasHold,'2026-08-20',6,'Atlas mobile platform setup','APPROVED',users.atlasPm] ];
    const other = [[contractors.atlasFrontend,projects.atlasActive,'2026-09-01',4,'Atlas draft example','DRAFT',users.atlasPm],[contractors.atlasQa,projects.atlasActive,'2026-09-02',5,'Atlas submitted example','SUBMITTED',users.atlasPm],[contractors.atlasFrontend,projects.atlasActive,'2026-09-03',3,'Atlas rejected example','REJECTED',users.atlasPm],[contractors.novaData,projects.novaActive,'2026-09-07',2,'Nova draft example','DRAFT',users.novaPm],[contractors.novaData,projects.novaActive,'2026-09-08',6,'Nova submitted example','SUBMITTED',users.novaPm],[contractors.atlasBackendHistory,projects.atlasCompleted,'2026-06-12',2,'Historical rejected correction','REJECTED',users.atlasPm]];
    for (const [contractor,project,date,hours,description,status,pm] of [...approved,...other]) await ensureTimesheet(c,{contractor,project,date,hours,description,status,pm});
    const milestones = {};
    for (const [key,project,name,description,sequence,due,threshold,status] of [ ['atlasBilled','atlasActive','Atlas Production Release','Reached billing checkpoint for frontend delivery.',1,'2026-08-31',72,'MET'], ['atlasEligible','atlasActive','Atlas QA Readiness','Reached and eligible but not yet invoiced.',2,'2026-09-15',80,'MET'], ['atlasPending','atlasActive','Atlas Final Acceptance','Pending future approved work.',3,'2026-11-30',120,'PENDING'], ['atlasHoldDraft','atlasHold','Atlas Mobile Foundation','Reached before project hold.',1,'2026-08-31',6,'MET'], ['atlasRejected','atlasCompleted','Atlas Migration Completion','Historical completed-project billing.',1,'2026-06-15',20,'MET'], ['atlasPartial','atlasCompleted','Atlas Migration Warranty','Historical partially-settled closeout work.',2,'2026-06-30',25,'MET'], ['novaSubmitted','novaActive','Nova Analytics Beta','Submitted billing example.',1,'2026-09-10',32,'MET'], ['novaPending','novaActive','Nova General Availability','Pending additional approved work.',2,'2026-12-15',80,'PENDING'], ['novaApproved','novaCompleted','Nova Portal Launch','Completed and fully settled.',1,'2026-06-30',12,'MET'] ]) milestones[key] = await ensureMilestone(c,projects[project],{name,description,sequence,due,threshold,status});
    const billings = { atlasBilled:await ensureBilling(c,milestones.atlasBilled,contractors.atlasFrontend,72,250), atlasEligible:await ensureBilling(c,milestones.atlasEligible,contractors.atlasQa,8,180), atlasHoldDraft:await ensureBilling(c,milestones.atlasHoldDraft,contractors.atlasDevops,6,210), atlasRejected:await ensureBilling(c,milestones.atlasRejected,contractors.atlasBackendHistory,20,250), atlasPartial:await ensureBilling(c,milestones.atlasPartial,contractors.atlasBackendHistory,5,250), novaSubmitted:await ensureBilling(c,milestones.novaSubmitted,contractors.novaData,32,225), novaApproved:await ensureBilling(c,milestones.novaApproved,contractors.novaDevopsHistory,12,250) };
    const common = {vendor:users.vendor};
    await ensureInvoice(c,{...common,number:'DEMO-ATLAS-2026-0001',project:projects.atlasActive,projectName:'Atlas Commerce Modernization',contractor:contractors.atlasFrontend,contractorName:'Avery Frontend',company:clients.atlas,pm:users.atlasPm,billing:billings.atlasBilled,milestoneName:'Atlas Production Release',skillName:'Frontend',hours:72,rate:250,subtotal:18000,taxRate:10,tax:1800,adjustment:200,adjustmentDescription:'Release coordination',total:20000,due:DATE.futureDue,status:'APPROVED'});
    await ensureInvoice(c,{...common,number:null,project:projects.atlasHold,projectName:'Atlas Mobile Expansion',contractor:contractors.atlasDevops,contractorName:'Devon DevOps',company:clients.atlas,pm:users.atlasPm,billing:billings.atlasHoldDraft,milestoneName:'Atlas Mobile Foundation',skillName:'DevOps',hours:6,rate:210,subtotal:1260,taxRate:0,tax:0,adjustment:0,total:1260,due:null,status:'DRAFT'});
    await ensureInvoice(c,{...common,number:'DEMO-ATLAS-2026-0002',project:projects.atlasCompleted,projectName:'Atlas Legacy Migration',contractor:contractors.atlasBackendHistory,contractorName:'Harper Backend',company:clients.atlas,pm:users.atlasPm,billing:billings.atlasRejected,milestoneName:'Atlas Migration Completion',skillName:'Backend',hours:20,rate:250,subtotal:5000,taxRate:0,tax:0,adjustment:0,total:5000,due:DATE.overdue,status:'REJECTED'});
    const atlasPartial = await ensureInvoice(c,{...common,number:'DEMO-ATLAS-2026-0003',project:projects.atlasCompleted,projectName:'Atlas Legacy Migration',contractor:contractors.atlasBackendHistory,contractorName:'Harper Backend',company:clients.atlas,pm:users.atlasPm,billing:billings.atlasPartial,milestoneName:'Atlas Migration Warranty',skillName:'Backend',hours:5,rate:250,subtotal:1250,taxRate:0,tax:0,adjustment:0,total:1250,due:DATE.overdue,status:'APPROVED'}); await ensurePayment(c,atlasPartial,users.vendor,500,'DEMO-ATLAS-PARTIAL-001');
    await ensureInvoice(c,{...common,number:'DEMO-NOVA-2026-0001',project:projects.novaActive,projectName:'Nova Analytics Platform',contractor:contractors.novaData,contractorName:'Dakota Data',company:clients.nova,pm:users.novaPm,billing:billings.novaSubmitted,milestoneName:'Nova Analytics Beta',skillName:'Data',hours:32,rate:225,subtotal:7200,taxRate:10,tax:720,adjustment:80,adjustmentDescription:'Platform enablement',total:8000,due:DATE.futureDue,status:'SUBMITTED'});
    const novaPaid = await ensureInvoice(c,{...common,number:'DEMO-NOVA-2026-0002',project:projects.novaCompleted,projectName:'Nova Customer Portal',contractor:contractors.novaDevopsHistory,contractorName:'Morgan DevOps',company:clients.nova,pm:users.novaPm,billing:billings.novaApproved,milestoneName:'Nova Portal Launch',skillName:'DevOps',hours:12,rate:250,subtotal:3000,taxRate:0,tax:0,adjustment:0,total:3000,due:DATE.overdue,status:'APPROVED'}); await ensurePayment(c,novaPaid,users.vendor,3000,'DEMO-NOVA-FULL-001');
    let [stored] = await c.query("SELECT storage_key,size_bytes FROM contractor_documents WHERE original_filename='atlasfrontend-identity.pdf' LIMIT 1"); const file = stored[0] || await storage.store({ contentBase64: Buffer.from('%PDF-1.4\nDeterministic demo compliance document\n%%EOF').toString('base64'), mimeType:'application/pdf' });
    for (const key of ['atlasFrontend','atlasQa','atlasUpcoming','atlasDevops','atlasBackendHistory','novaData','novaDevopsHistory','novaQaHistory']) for (const type of ['IDENTITY','TAX','QUALIFICATION']) await ensureDocument(c,file,contractors[key],`${key.toLowerCase()}-${type.toLowerCase()}.pdf`,type,'VERIFIED',key === 'atlasFrontend' ? '2026-09-25' : '2027-09-01',users.vendor);
    await ensureDocument(c,file,contractors.unassigned,'unassigned-identity-pending.pdf','IDENTITY','PENDING','2027-09-01',users.vendor); await ensureDocument(c,file,contractors.rejected,'rejected-qualification.pdf','QUALIFICATION','REJECTED','2027-09-01',users.vendor); await ensureDocument(c,file,contractors.atlasBackendHistory,'atlas-backend-expired-tax.pdf','TAX','EXPIRED','2026-06-01',users.vendor);
    const [availability] = await c.query(`SELECT id FROM contractor_unavailability WHERE contractor_id=? AND start_date='2026-09-20' AND end_date='2026-09-25' AND status='ACTIVE' LIMIT 1`, [contractors.unassigned]); if (!availability.length) await c.query(`INSERT INTO contractor_unavailability(contractor_id,start_date,end_date,reason,status) VALUES(?,'2026-09-20','2026-09-25','Planned demo leave','ACTIVE')`, [contractors.unassigned]);
    const [primaryAssignment] = await c.query('SELECT id FROM project_assignments WHERE contractor_id=? AND project_id=? LIMIT 1',[contractors.primary,projects.demo]); if (!primaryAssignment.length) { const rate = await ensureRate(c,clients.atlas,users.vendor,skills.BACKEND,120,75); await ensureAssignment(c,{contractor:contractors.primary,project:projects.demo,requirement:req.demo.BACKEND,allocated:40,bill:120,cost:75,rateCard:rate,status:'ACTIVE',start:DATE.activeStart,end:DATE.activeEnd,pm:users.atlasPm}); }
    await c.commit();
    const summary = await createSummary(c,users.vendor,clients,projects.atlasActive); logger.info('demo_seed_complete',{created:!expandedBefore,reconciled:true,vendor_email:EMAIL.vendor,pm_email:EMAIL.atlasPm,second_pm_email:EMAIL.novaPm,contractor_email:EMAIL.primary}); console.log(`DEMO_SEED_SUMMARY ${JSON.stringify(summary,null,2)}`);
  } catch (error) { await c.rollback().catch(()=>{}); throw error; } finally { await c.end(); await dashboardPool.end(); }
}

run().catch((error)=>{ logger.error('demo_seed_failed',{error_message:error.message}); process.exit(1); });
