const env = require("../config/env"); const ApiError = require("../utils/ApiError"); const { createFinding } = require("../utils/intelligenceFinding"); const contractorRepository = require("../repositories/contractorRepository"); const repository = require("../repositories/contractorTimesheetIntelligenceRepository");
const SOURCE = { engine: "contractor_timesheet_intelligence", version: "1" }; const rank = { HIGH: 0, MEDIUM: 1, LOW: 2, INFO: 3 };
const finding = (code, severity, title, summary, evidence, recommended_action) => createFinding({ code, severity, title, summary, evidence, recommended_action, source: SOURCE });
function today() { return new Date().toISOString().slice(0, 10); }
async function analyze(userId, proposal) {
  if (!env.intelligence.contractorTimesheetIntelligence) throw ApiError.notFound("Contractor Timesheet Intelligence is not available.");
  const contractor = await contractorRepository.findByUserId(userId); if (!contractor) throw ApiError.notFound("Contractor record not found for this account.");
  const data = await repository.context(contractor.id, proposal.projectId, proposal.workDate); if (!data.assignment) throw ApiError.notFound("You are not assigned to this project."); if (!data.project) throw ApiError.notFound("Project not found.");
  const findings = [];
  if (data.assignment.status !== "ACTIVE") findings.push(finding("ASSIGNMENT_NOT_ACTIVE_FOR_WORK", "HIGH", "Assignment is not active for work", "This assignment is not active.", [{ key: "assignment_status", label: "Assignment status", value: data.assignment.status }], "Choose an active assignment."));
  if (data.project.status !== "ACTIVE") findings.push(finding("PROJECT_NOT_OPEN_FOR_TIMESHEETS", "HIGH", "Project is not open for timesheets", "Timesheets can only be logged against active projects.", [{ key: "project_status", label: "Project status", value: data.project.status }], "Choose an active project."));
  if (proposal.workDate > today()) findings.push(finding("TIMESHEET_FUTURE_DATE", "HIGH", "Work date is in the future", "The proposed work date is after the server date.", [{ key: "work_date", label: "Work date", value: proposal.workDate }], "Choose a date that is not in the future."));
  if (proposal.workDate < data.project.start_date || (data.project.end_date && proposal.workDate > data.project.end_date)) findings.push(finding("TIMESHEET_OUTSIDE_PROJECT_WINDOW", "HIGH", "Work date is outside the project window", "The proposed work date is outside the project's valid date range.", [{ key: "work_date", label: "Work date", value: proposal.workDate }, { key: "project_start_date", label: "Project start date", value: data.project.start_date }, { key: "project_end_date", label: "Project end date", value: data.project.end_date }], "Choose a work date within the project period."));
  if (data.sameDay.count) findings.push(finding("DUPLICATE_TIMESHEET_ENTRY", "HIGH", "Timesheet already recorded for this date", "A timesheet already exists for this project and work date.", [{ key: "work_date", label: "Work date", value: proposal.workDate }, { key: "existing_entry_count", label: "Existing entries", value: data.sameDay.count }], "Review the existing timesheet before submitting another entry."));
  if (data.project.max_hours_per_day !== null && data.sameDay.hours + proposal.hoursLogged > Number(data.project.max_hours_per_day)) findings.push(finding("DAILY_HOURS_EXCEED_POLICY", "HIGH", "Daily hours exceed project policy", "Existing and proposed hours exceed the project's daily limit.", [{ key: "existing_hours", label: "Existing hours", value: data.sameDay.hours, unit: "hours" }, { key: "proposed_hours", label: "Proposed hours", value: proposal.hoursLogged, unit: "hours" }, { key: "resulting_daily_hours", label: "Resulting daily hours", value: data.sameDay.hours + proposal.hoursLogged, unit: "hours" }, { key: "policy_maximum", label: "Daily limit", value: Number(data.project.max_hours_per_day), unit: "hours" }], "Adjust the proposed hours before submitting."));
  findings.sort((a,b) => rank[a.severity] - rank[b.severity] || a.code.localeCompare(b.code)); const by_severity = Object.fromEntries(["HIGH","MEDIUM","LOW","INFO"].map((s) => [s, findings.filter((f) => f.severity === s).length]));
  return { contract_version: "1", context: { assignment_id: data.assignment.id, project: { id: data.project.id, name: data.project.name }, work_date: proposal.workDate, hours: proposal.hoursLogged }, summary: { finding_count: findings.length, by_severity }, findings };
}
module.exports = { analyze };
