const { pool } = require("../config/db"); const contractorRepository = require("../repositories/contractorRepository"); const documents = require("../repositories/contractorDocumentRepository"); const storage = require("./documentStorageService"); const audit = require("./auditService"); const ApiError = require("../utils/ApiError");
const REQUIRED = ["IDENTITY", "TAX", "QUALIFICATION"];
function compliance(rows) { const latest = new Map(); for (const row of rows) if (!latest.has(row.document_type)) latest.set(row.document_type, row); const missing = REQUIRED.filter((type) => { const row = latest.get(type); return !row || row.status !== "VERIFIED" || (row.expiry_date && String(row.expiry_date).slice(0, 10) < new Date().toISOString().slice(0, 10)); }); return { status: missing.length ? "NOT_VERIFIED" : "VERIFIED", missing_document_types: missing }; }
async function upload(vendorId, input, actor) { const conn = await pool.getConnection(); try { await conn.beginTransaction(); const contractor = await contractorRepository.findByVendorAndIdForUpdate(conn, vendorId, input.contractorId); if (!contractor) throw ApiError.notFound("Contractor not found."); const file = await storage.store(input); const id = await documents.create(conn, { ...input, storageKey: file.key, sizeBytes: file.sizeBytes }); if (actor) await audit.write(conn, actor, "CONTRACTOR_DOCUMENT_UPLOADED", "contractor_document", id, null, { contractor_id: input.contractorId, document_type: input.documentType, expiry_date: input.expiryDate }); await conn.commit(); return { id, document_type: input.documentType, status: "PENDING" }; } catch (err) { await conn.rollback().catch(() => {}); if (err.message === "Invalid document content.") throw ApiError.badRequest(err.message); throw err; } finally { conn.release(); } }
async function list(vendorId, contractorId) { const contractor = await contractorRepository.findByVendorAndId(vendorId, contractorId); if (!contractor) throw ApiError.notFound("Contractor not found."); const rows = await documents.listByContractor(contractorId); return { documents: rows, compliance: compliance(rows) }; }
async function review(vendorId, documentId, input, actor) { const conn = await pool.getConnection(); try { await conn.beginTransaction(); const before = await documents.lockOwnedByVendor(conn, vendorId, documentId); if (!before) throw ApiError.notFound("Document not found."); if (!(await documents.setReview(conn, documentId, { ...input, actorId: actor.userId }))) throw ApiError.conflict("Document has already been reviewed."); if (actor) await audit.write(conn, actor, "CONTRACTOR_DOCUMENT_REVIEWED", "contractor_document", documentId, { status: before.status }, { status: input.status, rejection_reason: input.rejectionReason }); await conn.commit(); return { id: documentId, status: input.status, rejection_reason: input.rejectionReason }; } catch (err) { await conn.rollback().catch(() => {}); throw err; } finally { conn.release(); } }
async function assertVerifiedForAssignment(conn, contractorId) { const result = compliance(await documents.complianceForUpdate(conn, contractorId)); if (result.status !== "VERIFIED") throw ApiError.badRequest(`Contractor compliance is not verified. Missing or invalid documents: ${result.missing_document_types.join(", ")}.`); }
async function summaryForPm(pmId, contractorId) { const rows = await documents.listForPm(pmId, contractorId); if (!rows.length) throw ApiError.notFound("Contractor compliance summary not found."); return { compliance: compliance(rows), documents: rows.map(({ document_type, status, expiry_date, verified_at }) => ({ document_type, status, expiry_date, verified_at })) }; }
module.exports = { upload, list, review, assertVerifiedForAssignment, compliance, summaryForPm };
