const { pool } = require('../config/db');
const { filters } = require('./dashboardAnalyticsService');
const ApiError = require('../utils/ApiError');
const DATASETS = new Set(['assignments', 'approved-timesheets', 'invoices', 'invoice-items', 'payments', 'project-financials']);
const safe = (value) => { const text = String(value ?? ''); return /^[=+\-*@]/.test(text) ? `'${text}` : text; };
const asCsv = (rows, headers) => [headers, ...rows.map((row) => headers.map((key) => row[key]))].map((row) => row.map((value) => `"${safe(value).replace(/"/g, '""')}"`).join(',')).join('\r\n');
function projectScope(role, userId, f, alias = 'p') { const where=[]; const values=[]; if(role==='VENDOR'){where.push(`EXISTS (SELECT 1 FROM project_assignments scope_pa JOIN contractors scope_c ON scope_c.id=scope_pa.contractor_id WHERE scope_pa.project_id=${alias}.id AND scope_c.vendor_id=?)`);values.push(userId);} else if(role==='PM'){where.push(`${alias}.pm_id=?`);values.push(userId);} else throw ApiError.forbidden('Dashboard exports are available to Vendor and PM users only.'); if(f.clientId){where.push(`pm.company_id=?`);values.push(f.clientId);}if(f.projectId){where.push(`${alias}.id=?`);values.push(f.projectId);}if(f.skillId){where.push(`EXISTS (SELECT 1 FROM project_requirements scope_pr WHERE scope_pr.project_id=${alias}.id AND scope_pr.skill_id=?)`);values.push(f.skillId);}if(f.status){where.push(`${alias}.status=?`);values.push(f.status);}return {where:where.join(' AND '),values}; }
function dateClause(f,column,values){let sql='';if(f.startDate){sql+=` AND ${column}>=?`;values.push(f.startDate);}if(f.endDate){sql+=` AND ${column}<=?`;values.push(f.endDate);}return sql;}
async function exportRows(role,userId,type,query){if(!DATASETS.has(type))throw ApiError.badRequest('Unsupported export dataset.');const f=filters(query);const s=projectScope(role,userId,f);const values=[...s.values];let sql;let headers;const vendorClause=role==='VENDOR'?' AND c.vendor_id=?':'';
if(type==='assignments'){sql=`SELECT p.name AS project_name,u.name AS contractor_name,pa.status,pa.start_date,pa.end_date,pa.allocated_hours FROM project_assignments pa JOIN contractors c ON c.id=pa.contractor_id JOIN users u ON u.id=c.user_id JOIN projects p ON p.id=pa.project_id JOIN project_managers pm ON pm.user_id=p.pm_id WHERE ${s.where}${dateClause(f,'pa.start_date',values)}${vendorClause}`;if(role==='VENDOR')values.push(userId);headers=['project_name','contractor_name','status','start_date','end_date','allocated_hours'];}
else if(type==='approved-timesheets'){sql=`SELECT p.name AS project_name,u.name AS contractor_name,t.work_date,t.hours_logged,t.status FROM timesheets t JOIN contractors c ON c.id=t.contractor_id JOIN users u ON u.id=c.user_id JOIN projects p ON p.id=t.project_id JOIN project_managers pm ON pm.user_id=p.pm_id WHERE ${s.where} AND t.status='APPROVED'${dateClause(f,'t.work_date',values)}${vendorClause}`;if(role==='VENDOR')values.push(userId);headers=['project_name','contractor_name','work_date','hours_logged','status'];}
else if(type==='invoices'||type==='invoice-items'||type==='payments'){const vendorInvoice=role==='VENDOR'?' AND i.vendor_id=?':'';if(type==='invoices'){sql=`SELECT i.invoice_number,p.name AS project_name,i.status,i.invoice_date,i.due_date,i.total_amount,i.currency FROM invoices i JOIN projects p ON p.id=i.project_id JOIN project_managers pm ON pm.user_id=p.pm_id WHERE ${s.where}${dateClause(f,'i.submitted_at',values)}${vendorInvoice}`;headers=['invoice_number','project_name','status','invoice_date','due_date','total_amount','currency'];}if(type==='invoice-items'){sql=`SELECT i.invoice_number,p.name AS project_name,ii.milestone_billing_id,ii.approved_hours,ii.bill_rate,ii.amount,i.currency FROM invoice_items ii JOIN invoices i ON i.id=ii.invoice_id JOIN projects p ON p.id=i.project_id JOIN project_managers pm ON pm.user_id=p.pm_id WHERE ${s.where}${dateClause(f,'i.submitted_at',values)}${vendorInvoice}`;headers=['invoice_number','project_name','milestone_billing_id','approved_hours','bill_rate','amount','currency'];}if(type==='payments'){sql=`SELECT i.invoice_number,p.name AS project_name,pay.paid_at,pay.amount,pay.currency,pay.reference,pay.method FROM payments pay JOIN invoices i ON i.id=pay.invoice_id JOIN projects p ON p.id=i.project_id JOIN project_managers pm ON pm.user_id=p.pm_id WHERE ${s.where}${dateClause(f,'pay.paid_at',values)}${vendorInvoice}`;headers=['invoice_number','project_name','paid_at','amount','currency','reference','method'];}if(role==='VENDOR')values.push(userId);}
else {sql=`SELECT p.name AS project_name,p.budget,p.currency,COALESCE(SUM(CASE WHEN i.status IN ('SUBMITTED','APPROVED') THEN i.total_amount ELSE 0 END),0) AS invoiced_amount,COALESCE(SUM(CASE WHEN i.status='APPROVED' THEN i.total_amount ELSE 0 END),0) AS approved_invoice_amount FROM projects p JOIN project_managers pm ON pm.user_id=p.pm_id LEFT JOIN invoices i ON i.project_id=p.id${role==='VENDOR'?' AND i.vendor_id=?':''} WHERE ${s.where} GROUP BY p.id,p.name,p.budget,p.currency`;if(role==='VENDOR')values.unshift(userId);headers=['project_name','budget','currency','invoiced_amount','approved_invoice_amount'];}
const [rows]=await pool.query(sql,values);return asCsv(rows,headers);}
module.exports={exportRows,DATASETS};
