const {pool}=require("../config/db"),repo=require("../repositories/rateCardRepository"),ApiError=require("../utils/ApiError"),audit=require("./auditService");
const date=v=>typeof v==='string'&&/^\d{4}-\d\d-\d\d$/.test(v);const money=v=>Number.isFinite(Number(v))&&Number(v)>0&&Math.round(Number(v)*100)===Number(v)*100;
function validate(b){const p={clientCompanyId:Number(b.client_company_id),skillId:Number(b.skill_id),effectiveFrom:b.effective_from,effectiveTo:b.effective_to||null,billRate:Number(b.bill_rate),costRate:Number(b.cost_rate),currency:String(b.currency||'').toUpperCase(),status:String(b.status||'ACTIVE').toUpperCase()};if(!Number.isInteger(p.clientCompanyId)||!Number.isInteger(p.skillId)||!date(p.effectiveFrom)||p.effectiveTo&&!date(p.effectiveTo)||p.effectiveTo&&p.effectiveTo<p.effectiveFrom||!money(p.billRate)||!money(p.costRate)||!/^[A-Z]{3}$/.test(p.currency)||!['ACTIVE','INACTIVE'].includes(p.status))throw ApiError.badRequest('Validation failed',['Invalid rate card fields.']);return p;}
async function create(vendorId,body,actor){const p=validate(body),c=await pool.getConnection();try{await c.beginTransaction();if(!await repo.clientRelationship(vendorId,p.clientCompanyId,c))throw ApiError.notFound('Client relationship not found.');if(p.status==='ACTIVE'&&await repo.findOverlap(c,{...p,vendorId}))throw ApiError.conflict('An active rate card already covers this skill and effective period.');const id=await repo.create(c,{...p,vendorId});await audit.write(c,actor,'RATE_CARD_CREATED','rate_card',id,null,{...p,vendor_id:vendorId});await c.commit();return{id,...p};}catch(e){await c.rollback().catch(()=>{});throw e;}finally{c.release();}}
async function update(vendorId,id,body,actor){const p=validate(body),c=await pool.getConnection();try{await c.beginTransaction();const before=await repo.lockOwned(c,vendorId,id);if(!before)throw ApiError.notFound('Rate card not found.');if(!await repo.clientRelationship(vendorId,p.clientCompanyId,c))throw ApiError.notFound('Client relationship not found.');if(await repo.hasAssignmentHistory(c,id))throw ApiError.conflict('A rate card used by an assignment is immutable; create a future rate card instead.');if(p.status==='ACTIVE'&&await repo.findOverlap(c,{...p,vendorId},id))throw ApiError.conflict('An active rate card already covers this skill and effective period.');await repo.update(c,id,p);await audit.write(c,actor,'RATE_CARD_UPDATED','rate_card',id,{client_company_id:before.client_company_id,skill_id:before.skill_id,effective_from:before.effective_from,effective_to:before.effective_to,bill_rate:Number(before.bill_rate),cost_rate:Number(before.cost_rate),currency:before.currency,status:before.status},{...p,vendor_id:vendorId});await c.commit();return{id,...p};}catch(e){await c.rollback().catch(()=>{});throw e;}finally{c.release();}}
async function list(vendorId,companyId){if(!await repo.clientRelationship(vendorId,companyId))throw ApiError.notFound('Client relationship not found.');return repo.list(vendorId,companyId);}
async function listSkills(){return repo.listSkills();}
async function resolveForAssignment(conn,{projectId,requirementId,vendorId,date}){const context=await repo.contextForAssignment(conn,projectId,requirementId);if(!context)throw ApiError.conflict('Rate-card context is unavailable.');return repo.resolve(conn,{clientCompanyId:context.company_id,vendorId,skillId:context.skill_id,date});}
module.exports={create,update,list,listSkills,resolveForAssignment};
