process.env.NODE_ENV = "test";
process.env.DB_NAME = process.env.DB_NAME || "vms_test";
process.env.JWT_SECRET = process.env.JWT_SECRET || "m27-test-only-secret";
process.env.INTELLIGENCE_PM_PROJECT_CONTROL_ENABLED = "true";
const assert = require("node:assert/strict"); const { after, before, test } = require("node:test");
const { resetTestDatabase } = require("../helpers/testDatabase"); const { pool } = require("../../src/config/db"); const app = require("../../src/app"); const env = require("../../src/config/env"); const { validateEvidence } = require("../../src/utils/intelligenceFinding");
let server, base, n = 0; const state = {}; const email = (x) => `m27-${x}-${Date.now()}-${++n}@test.local`; const day = (n) => `DATE_ADD(CURDATE(),INTERVAL ${n} DAY)`;
async function request(method, path, body, token) { const r = await fetch(`${base}${path}`, { method, headers: { "Content-Type": "application/json", ...(token ? { Authorization: `Bearer ${token}` } : {}) }, body: body === undefined ? undefined : JSON.stringify(body) }); return { status: r.status, data: await r.json().catch(() => null) }; }
async function signup(role, label) { const e = email(label); const made = await request("POST", "/auth/signup", { name: label, email: e, password: "Password123!", role, ...(role === "PM" ? { companyName: `${label} Co` } : {}) }); assert.equal(made.status, 201, JSON.stringify(made.data)); const login = await request("POST", "/auth/login", { email: e, password: "Password123!" }); assert.equal(login.status, 200, JSON.stringify(login.data)); return { token: login.data.token, id: login.data.user.id }; }
async function project(label, count = 1) { const r = await request("POST", "/pm/projects", { name: `M27 ${label}`, start_date: new Date().toISOString().slice(0, 10), expected_hours: 80, requirements: [{ skill: "BACKEND", required_count: count }] }, state.pm.token); assert.equal(r.status, 201, JSON.stringify(r.data)); return r.data; }
async function contractor(label) { const r = await request("POST", "/vendor/contractors", { name: `M27 ${label}`, email: email(label), password: "Password123!", hourly_rate: 80 }, state.vendor.token); assert.equal(r.status, 201, JSON.stringify(r.data)); return r.data.id; }
async function assign(p, c, end, status = "ACTIVE") { await pool.query(`INSERT INTO project_assignments (contractor_id,project_id,requirement_id,bill_rate_snapshot,cost_rate_snapshot,currency,assigned_date,start_date,end_date,status) VALUES (?,?,?,?,?,?,CURDATE(),CURDATE(),${day(end)},?)`, [c, p.id, p.requirements[0].id, 120, 80, "USD", status]); }
async function analyze(p) { const r = await request("GET", `/pm/projects/${p.id}/control-intelligence`, undefined, state.pm.token); assert.equal(r.status, 200, JSON.stringify(r.data)); return r.data; }
const finding = (r, code) => r.findings.find((x) => x.code === code); const ev = (f, key) => f.evidence.find((x) => x.key === key)?.value; const noFinding = (r, code) => assert.equal(finding(r, code), undefined, `unexpected ${code}`);
function allKeys(v, out = []) { if (Array.isArray(v)) v.forEach((x) => allKeys(x, out)); else if (v && typeof v === "object") Object.entries(v).forEach(([k, x]) => { out.push(k); allKeys(x, out); }); return out; }
before(async () => { await resetTestDatabase(); await new Promise((ok) => { server = app.listen(0, "127.0.0.1", ok); }); base = `http://127.0.0.1:${server.address().port}/api`; state.pm = await signup("PM", "PM"); state.other = await signup("PM", "Other"); state.vendor = await signup("VENDOR", "Vendor"); const contractorEmail = email("capability-contractor"); const created = await request("POST", "/vendor/contractors", { name: "M27 Capability Contractor", email: contractorEmail, password: "Password123!", hourly_rate: 80 }, state.vendor.token); assert.equal(created.status, 201, JSON.stringify(created.data)); const contractorLogin = await request("POST", "/auth/login", { email: contractorEmail, password: "Password123!" }); assert.equal(contractorLogin.status, 200, JSON.stringify(contractorLogin.data)); state.contractorUser = { token: contractorLogin.data.token }; [[state.client]] = await pool.query("SELECT company_id FROM project_managers WHERE user_id=?", [state.pm.id]); });
after(async () => { if (server) await new Promise((ok) => server.close(ok)); await pool.end(); });

test("M27 enforces feature/RBAC identity and advertises only PM capability", async () => { const p = await project("auth"); env.intelligence.pmProjectControl = false; assert.equal((await request("GET", `/pm/projects/${p.id}/control-intelligence`, undefined, state.pm.token)).status, 404); env.intelligence.pmProjectControl = true; assert.equal((await request("GET", `/pm/projects/${p.id}/control-intelligence`)).status, 401); assert.equal((await request("GET", `/pm/projects/${p.id}/control-intelligence`, undefined, state.vendor.token)).status, 403); assert.equal((await request("GET", `/pm/projects/${p.id}/control-intelligence?pmId=999&role=VENDOR`, undefined, state.other.token)).status, 404); for (const [u, expected] of [[state.pm, true], [state.vendor, false], [state.contractorUser, false]]) { const r = await request("GET", "/intelligence/capabilities", undefined, u.token); assert.equal(r.status, 200); assert.equal(r.data.capabilities.pm_project_control, expected); } });
test("M27 scopes submitted/rejected timesheets and excludes approved and other-project data", async () => { const p = await project("time"); const other = await project("time-other"); const c = await contractor("time"); await pool.query("INSERT INTO timesheets (contractor_id,project_id,work_date,hours_logged,status,submitted_at) VALUES (?, ?, CURDATE(),6,'SUBMITTED',NOW()),(?, ?,DATE_ADD(CURDATE(),INTERVAL 1 DAY),2,'REJECTED',NOW()),(?, ?,DATE_ADD(CURDATE(),INTERVAL 2 DAY),7,'APPROVED',NOW()),(?, ?,CURDATE(),9,'SUBMITTED',NOW())", [c,p.id,c,p.id,c,p.id,c,other.id]); const r = await analyze(p); assert.equal(ev(finding(r,"TIMESHEETS_AWAITING_REVIEW"),"submitted_count"),1); assert.equal(ev(finding(r,"TIMESHEETS_AWAITING_REVIEW"),"submitted_hours"),6); assert.equal(ev(finding(r,"REJECTED_TIMESHEETS_EXIST"),"rejected_count"),1); assert.equal(ev(finding(r,"REJECTED_TIMESHEETS_EXIST"),"rejected_hours"),2); });
test("M27 reports only requirements with remaining capacity", async () => { const open = await project("open",2), full = await project("full"), other = await project("req-other",3), c = await contractor("req"); await assign(open,c,40); await assign(full,c,40); await assign(other,c,40); const a = await analyze(open), b = await analyze(full); assert.equal(ev(finding(a,"OPEN_REQUIREMENTS_REMAIN"),"open_requirement_count"),1); assert.equal(ev(finding(a,"OPEN_REQUIREMENTS_REMAIN"),"remaining_slots"),1); noFinding(b,"OPEN_REQUIREMENTS_REMAIN"); });
test("M27 scopes pending candidates to submitted target-project candidates", async () => { const p = await project("candidate"), other = await project("candidate-other"), c = await contractor("candidate"); await pool.query("INSERT INTO candidate_submissions (project_id,requirement_id,contractor_id,vendor_id,status,proposed_start_date,submitted_at) VALUES (?,?,?,?, 'SUBMITTED',CURDATE(),NOW()),(?,?,?,?, 'ACCEPTED',CURDATE(),NOW()),(?,?,?,?, 'REJECTED',CURDATE(),NOW()),(?,?,?,?, 'SUBMITTED',CURDATE(),NOW())", [p.id,p.requirements[0].id,c,state.vendor.id,p.id,p.requirements[0].id,c,state.vendor.id,p.id,p.requirements[0].id,c,state.vendor.id,other.id,other.requirements[0].id,c,state.vendor.id]); const r = await analyze(p); assert.equal(ev(finding(r,"CANDIDATE_REVIEWS_PENDING"),"pending_candidate_count"),1); });
test("M27 applies the active-assignment 14-day window and excludes released assignments", async () => { const p = await project("assignment"); const ids = []; for (const label of ["at-boundary","outside","released-soon","past","released-past"]) ids.push(await contractor(label)); await assign(p,ids[0],14); await assign(p,ids[1],15); await assign(p,ids[2],10,"RELEASED"); await assign(p,ids[3],-1); await assign(p,ids[4],-2,"RELEASED"); const r = await analyze(p); assert.equal(r.findings.filter((x) => x.code === "ASSIGNMENT_ENDING_SOON").length,1); assert.equal(r.findings.filter((x) => x.code === "ACTIVE_ASSIGNMENT_PAST_END_DATE").length,1); });
test("M27 scopes expiring verified documents to assigned contractors", async () => { const p = await project("document"), assigned = await contractor("document-a"), unassigned = await contractor("document-u"); await assign(p,assigned,40); await pool.query(`INSERT INTO contractor_documents (contractor_id,document_type,storage_key,original_filename,mime_type,size_bytes,status,expiry_date) VALUES (?, 'IDENTITY','m27-a','a.pdf','application/pdf',1,'VERIFIED',${day(10)}),(?, 'TAX','m27-b','b.pdf','application/pdf',1,'VERIFIED',${day(31)}),(?, 'IDENTITY','m27-c','c.pdf','application/pdf',1,'VERIFIED',${day(10)})`,[assigned,assigned,unassigned]); const r = await analyze(p); assert.equal(ev(finding(r,"CONTRACTOR_DOCUMENT_EXPIRING"),"expiring_document_count"),1); });
test("M27 scopes submitted invoice review totals and excludes approved/rejected/other-project invoices", async () => { const p = await project("invoice"), other = await project("invoice-other"), c = await contractor("invoice"); const sql = "INSERT INTO invoices (project_id,contractor_id,vendor_id,client_company_id,currency,invoice_date,payment_terms_days,tax_rate,amount,subtotal_amount,tax_amount,adjustment_amount,total_amount,status,generated_at,submitted_at,document_version) VALUES (?,?,?,?, 'USD',CURDATE(),30,0,?,?,0,0,?,?,NOW(),NOW(),1)"; for (const [projectId,total,status] of [[p.id,125,"SUBMITTED"],[p.id,70,"APPROVED"],[p.id,30,"REJECTED"],[other.id,999,"SUBMITTED"]]) await pool.query(sql,[projectId,c,state.vendor.id,state.client.company_id,total,total,total,status]); const r=await analyze(p), f=finding(r,"INVOICES_AWAITING_REVIEW"); assert.equal(ev(f,"submitted_invoice_count"),1); assert.equal(ev(f,"submitted_invoice_total"),125); assert.equal(f.evidence.find((x)=>x.key==="submitted_invoice_total").unit,"USD"); });
test("M27 reuses close readiness, is read-only, and returns a clean close-ready project", async () => { const blocked=await project("blocked"), clean=await project("clean"), c=await contractor("close"); await assign(clean,c,40); await pool.query("INSERT INTO timesheets (contractor_id,project_id,work_date,hours_logged,status,submitted_at) VALUES (?, ?, CURDATE(),4,'SUBMITTED',NOW())",[c,blocked.id]); const tables=["projects","project_requirements","candidate_submissions","project_assignments","timesheets","invoices","contractor_documents","payments","audit_log","notifications"]; const before=await Promise.all(tables.map(async (t)=>[t,(await pool.query(`SELECT * FROM ${t} ORDER BY id`))[0]])); const a=await analyze(blocked), b=await analyze(clean); assert.ok(finding(a,"PROJECT_NOT_READY_TO_CLOSE")); noFinding(b,"PROJECT_NOT_READY_TO_CLOSE"); assert.equal(b.findings.length,0); assert.equal(b.summary.attention_count,0); const after=await Promise.all(tables.map(async (t)=>[t,(await pool.query(`SELECT * FROM ${t} ORDER BY id`))[0]])); assert.deepEqual(after,before); });
test("M27 uses deterministic ordering, accurate summaries, and safe response keys", async () => { const p=await project("ordering"), c=await contractor("ordering"); await assign(p,c,-1); await pool.query("INSERT INTO timesheets (contractor_id,project_id,work_date,hours_logged,status,submitted_at) VALUES (?, ?, CURDATE(),3,'SUBMITTED',NOW())",[c,p.id]); await pool.query(`INSERT INTO contractor_documents (contractor_id,document_type,storage_key,original_filename,mime_type,size_bytes,status,expiry_date) VALUES (?, 'IDENTITY','m27-order','order.pdf','application/pdf',1,'VERIFIED',${day(10)})`,[c]); const r=await analyze(p), ranks={HIGH:0,MEDIUM:1,LOW:2,INFO:3}; assert.deepEqual(r.findings.map((x)=>ranks[x.severity]),[...r.findings.map((x)=>ranks[x.severity])].sort((a,b)=>a-b)); assert.deepEqual(r.findings.filter((x)=>x.severity==="INFO").map((x)=>x.code),[...r.findings.filter((x)=>x.severity==="INFO").map((x)=>x.code)].sort()); assert.equal(r.summary.attention_count,r.findings.length); for(const s of ["HIGH","MEDIUM","LOW","INFO"])assert.equal(r.summary.by_severity[s],r.findings.filter((x)=>x.severity===s).length); for(const f of r.findings)validateEvidence(f.evidence); const forbidden=new Set(["health_score","risk_score","risk_percentage","confidence","confidence_score","cost_rate","costRate","cost_rate_snapshot","costRateSnapshot","margin","margin_percentage","marginPercentage","vendor_rate_intelligence"]); assert.equal(allKeys(r).some((k)=>forbidden.has(k)),false); });
