const {pool}=require('../config/db');
async function list(vendorId){const [r]=await pool.query(`SELECT cc.id,cc.name,COUNT(DISTINCT p.id) active_projects,COUNT(DISTINCT pr.id) open_requirements,COUNT(DISTINCT pa.id) deployed_contractors,GROUP_CONCAT(DISTINCT u.name ORDER BY u.name SEPARATOR ', ') pm_contacts FROM client_vendor_relationships r JOIN client_companies cc ON cc.id=r.client_company_id LEFT JOIN project_managers pm ON pm.company_id=cc.id LEFT JOIN users u ON u.id=pm.user_id LEFT JOIN projects p ON p.pm_id=pm.user_id AND p.status='ACTIVE' LEFT JOIN project_requirements pr ON pr.project_id=p.id LEFT JOIN project_assignments pa ON pa.project_id=p.id AND pa.status='ACTIVE' WHERE r.vendor_id=? AND r.status='ACTIVE' GROUP BY cc.id,cc.name ORDER BY cc.name`,[vendorId]);return r.map(x=>({...x,active_projects:Number(x.active_projects),open_requirements:Number(x.open_requirements),deployed_contractors:Number(x.deployed_contractors)}));}
async function detail(vendorId, companyId){
 const [companies]=await pool.query("SELECT cc.id,cc.name FROM client_vendor_relationships r JOIN client_companies cc ON cc.id=r.client_company_id WHERE r.vendor_id=? AND r.client_company_id=? AND r.status='ACTIVE' LIMIT 1",[vendorId,companyId]);
 if(!companies[0])return null;
 const [contacts]=await pool.query("SELECT u.id,u.name,u.email FROM project_managers pm JOIN users u ON u.id=pm.user_id WHERE pm.company_id=? ORDER BY u.name",[companyId]);
 const [projects]=await pool.query(`SELECT p.id,p.name,p.status,p.start_date,p.end_date,COUNT(DISTINCT pr.id) AS open_requirements,COUNT(DISTINCT pa.id) AS deployed_contractors FROM projects p JOIN project_managers pm ON pm.user_id=p.pm_id LEFT JOIN project_requirements pr ON pr.project_id=p.id LEFT JOIN project_assignments pa ON pa.project_id=p.id AND pa.status='ACTIVE' WHERE pm.company_id=? AND p.status='ACTIVE' GROUP BY p.id,p.name,p.status,p.start_date,p.end_date ORDER BY p.start_date DESC,p.id DESC`,[companyId]);
 return {company:companies[0],pm_contacts:contacts,active_projects:projects.map(p=>({...p,open_requirements:Number(p.open_requirements),deployed_contractors:Number(p.deployed_contractors)}))};
}
module.exports={list,detail};
