const access=require('../repositories/vendorAccessRepository'); const project=require('../repositories/projectRepository'); const users=require('../repositories/userRepository'); const ApiError=require('../utils/ApiError'); const asyncHandler=require('../utils/asyncHandler'); const {pool}=require('../config/db'); const audit=require('../services/auditService');
const id=v=>{const n=Number(v);if(!Number.isInteger(n)||n<1)throw ApiError.badRequest('Invalid id.');return n;};
async function assertVendor(vendorId, conn){if(!await users.isVendor(vendorId,conn))throw ApiError.notFound('Vendor not found.');}
async function ownedProject(projectId,pmId){const p=await project.findById(projectId);if(!p||p.pm_id!==pmId)throw ApiError.notFound('Project not found.');return p;}
const connect=asyncHandler(async(req,res)=>{const vendorId=id(req.body.vendorId);const projectId=req.body.projectId ? id(req.body.projectId) : null;const company=await access.companyForPm(req.user.userId);if(!company)throw ApiError.notFound('Client company not found.');if(projectId)await ownedProject(projectId,req.user.userId);const conn=await pool.getConnection();try{await conn.beginTransaction();await assertVendor(vendorId,conn);await access.connect(conn,company.company_id,vendorId,req.user.userId);if(projectId)await access.grantProject(conn,projectId,vendorId);await audit.write(conn,{...req.user,requestId:req.requestId},'VENDOR_CLIENT_CONNECTED','client_vendor_relationship',vendorId,null,{client_company_id:company.company_id,project_id:projectId});await conn.commit();res.status(201).json({vendor_id:vendorId,status:'ACTIVE'});}catch(e){await conn.rollback();throw e;}finally{conn.release();}});
const grant=asyncHandler(async(req,res)=>{const projectId=id(req.params.projectId),vendorId=id(req.body.vendorId);await ownedProject(projectId,req.user.userId);const conn=await pool.getConnection();try{await conn.beginTransaction();await assertVendor(vendorId,conn);await access.grantProject(conn,projectId,vendorId);await audit.write(conn,{...req.user,requestId:req.requestId},'PROJECT_VENDOR_GRANTED','project_vendor',projectId,null,{vendor_id:vendorId});await conn.commit();res.status(201).json({project_id:projectId,vendor_id:vendorId,status:'ACTIVE'});}catch(e){await conn.rollback();throw e;}finally{conn.release();}});
const listVendors=asyncHandler(async(req,res)=>res.json({items:await users.listVendors()}));
const listConnections=asyncHandler(async(req,res)=>{const company=await access.companyForPm(req.user.userId);if(!company)throw ApiError.notFound('Client company not found.');res.json({items:await access.listForCompany(company.company_id)});});
const revoke=asyncHandler(async(req,res)=>{const vendorId=id(req.params.vendorId);const company=await access.companyForPm(req.user.userId);if(!company)throw ApiError.notFound('Client company not found.');const conn=await pool.getConnection();try{await conn.beginTransaction();await access.revokeConnection(conn,company.company_id,vendorId);await audit.write(conn,{...req.user,requestId:req.requestId},'VENDOR_CLIENT_REVOKED','client_vendor_relationship',vendorId,{client_company_id:company.company_id,status:'ACTIVE'},{client_company_id:company.company_id,status:'REVOKED'});await conn.commit();res.status(204).end();}catch(e){await conn.rollback();throw e;}finally{conn.release();}});
const revokeProject=asyncHandler(async(req,res)=>{const projectId=id(req.params.projectId),vendorId=id(req.params.vendorId);await ownedProject(projectId,req.user.userId);const conn=await pool.getConnection();try{await conn.beginTransaction();await access.revokeProject(conn,projectId,vendorId);await audit.write(conn,{...req.user,requestId:req.requestId},'PROJECT_VENDOR_REVOKED','project_vendor',projectId,{vendor_id:vendorId,status:'ACTIVE'},{vendor_id:vendorId,status:'REVOKED'});await conn.commit();res.status(204).end();}catch(e){await conn.rollback();throw e;}finally{conn.release();}});
module.exports={connect,grant,listVendors,listConnections,revoke,revokeProject};
