import { useCallback, useEffect, useState } from 'react';
import AlertBanner from '../AlertBanner';
import PrimaryButton from '../PrimaryButton';
import vendorContractorService from '../../services/vendorContractorService';

const date = (value) => value ? String(value).slice(0, 10) : '—';

export default function ContractorHistoryModal({ contractor, onClose }) {
  const [assignments, setAssignments] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(null);
  const [releaseFor, setReleaseFor] = useState(null); const [readiness, setReadiness] = useState(null); const [actualEndDate, setActualEndDate] = useState(new Date().toISOString().slice(0, 10)); const [reason, setReason] = useState(''); const [saving, setSaving] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(null); try { setAssignments(await vendorContractorService.getHistory(contractor.id)); } catch (err) { setError(err.message); } finally { setLoading(false); } }, [contractor.id]);
  useEffect(() => { load(); }, [load]);
  const beginRelease = async (assignment) => { setError(null); setReleaseFor(assignment); try { setReadiness(await vendorContractorService.getReleaseReadiness(assignment.project_id, contractor.id)); } catch (err) { setError(err.message); setReleaseFor(null); } };
  const submitRelease = async () => { if (!releaseFor || !reason.trim()) { setError('A release reason is required.'); return; } setSaving(true); setError(null); try { await vendorContractorService.release(releaseFor.project_id, contractor.id, { actualEndDate, reason }); setReleaseFor(null); setReadiness(null); setReason(''); await load(); } catch (err) { setError(err.message); } finally { setSaving(false); } };
  return <div role="dialog" aria-modal="true" className="fixed inset-0 z-50 overflow-y-auto bg-black/40 p-4"><div className="mx-auto my-8 max-w-3xl rounded-lg bg-surface p-5 shadow-xl"><div className="flex items-start justify-between gap-4"><div><h2 className="text-lg font-semibold text-text">{contractor.name} — assignment history</h2><p className="text-sm text-muted">Historical assignments stay available after a contractor becomes inactive.</p></div><button type="button" onClick={onClose} className="text-text-secondary">Close</button></div><AlertBanner message={error} />
    {loading ? <p className="py-8 text-sm text-muted">Loading assignment history…</p> : <div className="mt-4 space-y-3">{assignments.length ? assignments.map((item) => <div key={item.assignment_id} className="rounded-md border border-border p-4 text-sm"><div className="flex flex-wrap items-center justify-between gap-2"><strong>{item.project_name}</strong><span className="rounded bg-surface-muted px-2 py-1 text-xs">{item.status}</span></div><p className="mt-2 text-text-secondary">Start {date(item.start_date)} · Planned last day {date(item.planned_last_working_date)} · Actual last day {date(item.actual_end_date)}</p><p className="mt-1 text-text-secondary">Approved hours {item.approved_hours} · Billed {item.billed_amount} {item.currency || ''} · Paid {item.paid_amount} {item.currency || ''}</p>{item.release_reason && <p className="mt-1 text-text-secondary">Release reason: {item.release_reason}</p>}{item.status === 'ACTIVE' && <button type="button" onClick={() => beginRelease(item)} className="mt-3 rounded-md border border-border px-3 py-1.5 font-medium text-text-secondary">Release contractor</button>}</div>) : <p className="py-8 text-sm text-muted">No assignment history is available.</p>}</div>}
    {releaseFor && <div className="mt-5 rounded-md border border-border bg-surface-muted p-4"><h3 className="font-medium text-text">Release from {releaseFor.project_name}</h3>{readiness?.blockers?.length > 0 && <AlertBanner message={readiness.blockers.map((x) => x.message).join(' ')} />}{readiness?.warnings?.length > 0 && <p className="mt-2 text-sm text-muted">Warnings: {readiness.warnings.map((x) => x.message).join(' ')}</p>}<label className="mt-3 block text-sm">Actual last working date<input type="date" value={actualEndDate} onChange={(e) => setActualEndDate(e.target.value)} className="mt-1 block rounded border border-border p-2" /></label><label className="mt-3 block text-sm">Release reason<textarea value={reason} onChange={(e) => setReason(e.target.value)} className="mt-1 block w-full rounded border border-border p-2" maxLength="500" /></label><div className="mt-3 flex gap-2"><PrimaryButton type="button" fullWidth={false} onClick={submitRelease} disabled={saving || readiness?.can_release === false}>Confirm release</PrimaryButton><button type="button" onClick={() => setReleaseFor(null)} className="rounded border border-border px-3 py-2">Cancel</button></div></div>}
  </div></div>;
}
