import { fireEvent, render, screen } from "@testing-library/react";
import { MemoryRouter } from "react-router-dom";
import { describe, expect, it, vi } from "vitest";
import PMProjectControlPanel from "./PMProjectControlPanel";

const control = { project: { id: 2, name: "Atlas", status: "ACTIVE" }, summary: { attention_count: 4, by_severity: { HIGH: 1, MEDIUM: 0, LOW: 0, INFO: 3 } }, findings: [{ code: "PROJECT_NOT_READY_TO_CLOSE", severity: "HIGH", title: "Close blocked", summary: "Resolve blockers.", evidence: [{ key: "count", label: "Close blockers", value: 2 }], recommended_action: "Review close readiness.", source: { engine: "pm_project_control", version: "1" } }, { code: "OPEN_REQUIREMENTS_REMAIN", severity: "INFO", title: "Requirements", summary: "One position.", evidence: [{ key: "slots", label: "Remaining slots", value: 1 }], recommended_action: "Review requirements.", source: { engine: "pm_project_control", version: "1" } }, { code: "REJECTED_TIMESHEETS_EXIST", severity: "INFO", title: "Rejected timesheets", summary: "Historical rejection.", evidence: [{ key: "count", label: "Rejected", value: 1 }], recommended_action: "Review correction status.", source: { engine: "pm_project_control", version: "1" } }, { code: "TIMESHEETS_AWAITING_REVIEW", severity: "INFO", title: "Timesheets", summary: "Safe.", evidence: [{ key: "flag", label: "Flag", value: true }], recommended_action: "Read it.", source: { engine: "pm_project_control", version: "1" } }] };
function view(props) { return render(<MemoryRouter><PMProjectControlPanel {...props} /></MemoryRouter>); }
describe("PMProjectControlPanel", () => {
  it("renders server order, evidence, meaningful submitted-timesheet navigation, and the reusable requirements action", () => { const onOpenRequirements = vi.fn(); view({ control, onRefresh: vi.fn(), onOpenRequirements }); expect(screen.getByText("Needs attention").parentElement).toHaveTextContent("4"); expect(screen.getAllByRole("article").map((item) => item.textContent)).toEqual(expect.arrayContaining([expect.stringContaining("Close blocked"), expect.stringContaining("Requirements")])); expect(screen.getByText("Close blockers").parentElement).toHaveTextContent("2"); expect(screen.getByRole("link", { name: "Review timesheets" })).toHaveAttribute("href", "/pm/timesheets"); expect(screen.getByText("Rejected timesheets").closest("article")).not.toHaveTextContent("Review timesheets"); expect(screen.queryByRole("link", { name: "Open workflow" })).not.toBeInTheDocument(); expect(screen.queryByText("Close blocked").closest("article")).not.toHaveTextContent("Open workflow"); screen.getByRole("button", { name: "View requirements" }).click(); expect(onOpenRequirements).toHaveBeenCalledOnce(); });
  it("renders loading, safe error, and neutral empty states", () => { const { rerender } = view({ isLoading: true, onRefresh: vi.fn() }); expect(screen.getByRole("status")).toHaveTextContent("Loading project attention"); rerender(<MemoryRouter><PMProjectControlPanel error onRefresh={vi.fn()} /></MemoryRouter>); expect(screen.getByRole("alert")).toHaveTextContent("could not be loaded"); rerender(<MemoryRouter><PMProjectControlPanel control={{ ...control, summary: { ...control.summary, attention_count: 0, by_severity: { HIGH: 0, MEDIUM: 0, LOW: 0, INFO: 0 } }, findings: [] }} onRefresh={vi.fn()} /></MemoryRouter>); expect(screen.getByText("No current attention items for this project.")).toBeInTheDocument(); });
  it("refreshes only through the explicit control", () => { const onRefresh = vi.fn(); view({ control, onRefresh }); screen.getByRole("button", { name: "Refresh attention" }).click(); expect(onRefresh).toHaveBeenCalledOnce(); });
  it("keeps deterministic content visible and requests an explanation only after the explicit AI action", () => { const onExplain = vi.fn(); view({ control, onRefresh: vi.fn(), aiEnabled: true, onExplain, explanations: { "2:PROJECT_NOT_READY_TO_CLOSE": { data: { explanation: "The project has unresolved recorded blockers.", source: "AI" } }, "2:OPEN_REQUIREMENTS_REMAIN": { data: { explanation: "The deterministic summary is shown again.", source: "DETERMINISTIC" } } } }); expect(onExplain).not.toHaveBeenCalled(); expect(screen.getAllByRole("button", { name: "Explain with AI" })).toHaveLength(4); expect(screen.getByText("AI explanation")).toBeInTheDocument(); expect(screen.getByText("System fallback explanation")).toBeInTheDocument(); expect(screen.getAllByText("Generated from the verified system finding. The underlying finding and action remain system-determined.")).toHaveLength(2); fireEvent.click(screen.getAllByRole("button", { name: "Explain with AI" })[0]); expect(onExplain).toHaveBeenCalledWith(control.findings[0]); expect(screen.getByText("Close blocked")).toBeInTheDocument(); });
  it("does not expose AI controls when unavailable and preserves findings during loading or error", () => { const onExplain = vi.fn(); const { rerender } = view({ control, onRefresh: vi.fn(), aiEnabled: false, onExplain }); expect(screen.queryByRole("button", { name: "Explain with AI" })).not.toBeInTheDocument(); rerender(<MemoryRouter><PMProjectControlPanel control={control} onRefresh={vi.fn()} aiEnabled explanations={{ "2:PROJECT_NOT_READY_TO_CLOSE": { loading: true } }} onExplain={onExplain} /></MemoryRouter>); expect(screen.getByRole("button", { name: "Generating explanation…" })).toBeDisabled(); expect(screen.getByText("Close blocked")).toBeInTheDocument(); rerender(<MemoryRouter><PMProjectControlPanel control={control} onRefresh={vi.fn()} aiEnabled explanations={{ "2:PROJECT_NOT_READY_TO_CLOSE": { error: true } }} onExplain={onExplain} /></MemoryRouter>); expect(screen.getByRole("alert")).toHaveTextContent("Explanation could not be loaded"); expect(screen.getAllByText("Recommended action:")).toHaveLength(control.findings.length); });
});
