import { fireEvent, render, screen } from "@testing-library/react";
import { expect, test, vi } from "vitest";
import ContractorTimesheetIntelligencePanel from "./ContractorTimesheetIntelligencePanel";

const finding = { code: "TIMESHEET_FUTURE_DATE", severity: "HIGH", title: "Work date is in the future", summary: "The proposed work date is after the server date.", evidence: [{ key: "work_date", label: "Work date", value: "2026-09-12" }], recommended_action: "Choose a date that is not in the future.", source: { engine: "contractor_timesheet_intelligence", version: "1" } };
const proposal = { projectId: "1", workDate: "2026-09-12", hoursLogged: "1", description: "" };
test("renders server findings in order with readable evidence and actions", () => { render(<ContractorTimesheetIntelligencePanel proposal={proposal} analysis={{ findings: [finding, { ...finding, code: "UNKNOWN", severity: "INFO", title: "Unknown valid finding" }] }} stale={false} isLoading={false} error={null} onAnalyze={vi.fn()} />); expect(screen.getAllByRole("article").map((item) => item.textContent)).toEqual([expect.stringContaining("Work date is in the future"), expect.stringContaining("Unknown valid finding")]); expect(screen.getAllByText("Work date")[0].parentElement).toHaveTextContent("2026-09-12"); expect(screen.getAllByText(/Recommended action:/)[0].parentElement).toHaveTextContent("Choose a date"); });
test("uses factual clean and stale states without blocking analysis", () => { const onAnalyze = vi.fn(); const { rerender } = render(<ContractorTimesheetIntelligencePanel proposal={proposal} analysis={{ findings: [] }} stale={false} isLoading={false} error={null} onAnalyze={onAnalyze} />); expect(screen.getByText(/No current timesheet intelligence findings/)).toHaveTextContent(/Normal submission validation still applies/); rerender(<ContractorTimesheetIntelligencePanel proposal={proposal} analysis={null} stale isLoading={false} error={null} onAnalyze={onAnalyze} />); expect(screen.getByText(/Timesheet details changed/)).toBeInTheDocument(); fireEvent.click(screen.getByRole("button", { name: "Check again" })); expect(onAnalyze).toHaveBeenCalledOnce(); });
test("handles incomplete context and failures without affecting the form", () => { render(<ContractorTimesheetIntelligencePanel proposal={{ ...proposal, workDate: "" }} analysis={null} stale={false} isLoading={false} error onAnalyze={vi.fn()} />); expect(screen.getByRole("button", { name: "Check before submitting" })).toBeDisabled(); expect(screen.getByRole("alert")).toHaveTextContent(/continue with the normal submission flow/i); });
