import { useEffect, useState } from "react";
import DashboardLayout from "../layouts/DashboardLayout";
import AlertBanner from "../components/AlertBanner";
import PrimaryButton from "../components/PrimaryButton";
import Spinner from "../components/Spinner";
import availabilityService from "../services/contractorAvailabilityService";

export default function ContractorAvailabilityPage() {
  const [items, setItems] = useState([]); const [error, setError] = useState(null); const [loading, setLoading] = useState(true);
  const [startDate, setStartDate] = useState(""); const [endDate, setEndDate] = useState(""); const [reason, setReason] = useState(""); const [saving, setSaving] = useState(false);
  const load = async () => { setLoading(true); try { setItems(await availabilityService.list()); } catch (err) { setError(err.message); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const submit = async (event) => { event.preventDefault(); setError(null); setSaving(true); try { const created = await availabilityService.create({ start_date: startDate, end_date: endDate, reason: reason || undefined }); setItems((current) => [...current, created].sort((a, b) => a.start_date.localeCompare(b.start_date))); setStartDate(""); setEndDate(""); setReason(""); } catch (err) { setError(err.message); } finally { setSaving(false); } };
  const cancel = async (id) => { setError(null); try { await availabilityService.cancel(id); setItems((current) => current.map((item) => item.id === id ? { ...item, status: "CANCELLED" } : item)); } catch (err) { setError(err.message); } };
  return <DashboardLayout title="My Availability"><div className="mx-auto flex max-w-3xl flex-col gap-5"><h1 className="text-xl font-semibold text-text">My Availability</h1><AlertBanner message={error} /><form onSubmit={submit} className="grid gap-3 rounded-lg bg-surface p-4 shadow-panel ring-1 ring-border sm:grid-cols-3"><label className="text-sm text-text-secondary">Start<input required type="date" value={startDate} onChange={(e) => setStartDate(e.target.value)} className="mt-1 block w-full rounded border border-border px-2 py-1.5 text-text" /></label><label className="text-sm text-text-secondary">End<input required type="date" min={startDate || undefined} value={endDate} onChange={(e) => setEndDate(e.target.value)} className="mt-1 block w-full rounded border border-border px-2 py-1.5 text-text" /></label><label className="text-sm text-text-secondary">Reason<input value={reason} onChange={(e) => setReason(e.target.value)} className="mt-1 block w-full rounded border border-border px-2 py-1.5 text-text" /></label><div className="sm:col-span-3"><PrimaryButton isLoading={saving} loadingText="Saving…">Add unavailable period</PrimaryButton></div></form>{loading ? <Spinner label="Loading availability…" /> : <div className="rounded-lg bg-surface p-4 shadow-panel ring-1 ring-border">{items.length === 0 ? <p className="text-sm text-muted">No unavailable periods recorded.</p> : items.map((item) => <div key={item.id} className="flex items-center justify-between gap-3 border-b border-border py-3 last:border-0"><div><p className="text-sm text-text">{item.start_date} to {item.end_date}</p><p className="text-xs text-muted">{item.reason || "No reason provided"} · {item.status}</p></div>{item.status === "ACTIVE" && <button type="button" onClick={() => cancel(item.id)} className="rounded border border-border px-2 py-1 text-xs text-text-secondary hover:bg-surface-muted">Cancel</button>}</div>)}</div>}</div></DashboardLayout>;
}
