import { useEffect, useState } from "react";
import DashboardLayout from "../layouts/DashboardLayout";
import Spinner from "../components/Spinner";
import AlertBanner from "../components/AlertBanner";
import PrimaryButton from "../components/PrimaryButton";
import vendorContractorService from "../services/vendorContractorService";
import documents from "../services/vendorDocumentService";
const types = ["IDENTITY", "TAX", "QUALIFICATION"];
export default function VendorCompliancePage() {
  const [contractors, setContractors] = useState([]); const [contractorId, setContractorId] = useState(""); const [data, setData] = useState(null); const [error, setError] = useState(null); const [loading, setLoading] = useState(true); const [file, setFile] = useState(null); const [type, setType] = useState("IDENTITY"); const [expiryDate, setExpiryDate] = useState(""); const [saving, setSaving] = useState(false);
  const load = async (id) => { if (!id) return; try { setLoading(true); setData(await documents.list(id)); } catch (e) { setError(e.message); } finally { setLoading(false); } };
  useEffect(() => { (async () => { try { const result = await vendorContractorService.listContractors({ page: 1, pageSize: 100, sort: "name", order: "asc" }); setContractors(result.items); if (result.items[0]) { setContractorId(String(result.items[0].id)); await load(result.items[0].id); } } catch (e) { setError(e.message); } finally { setLoading(false); } })(); }, []);
  const upload = async (event) => { event.preventDefault(); if (!file) return setError("Choose a PDF, PNG, or JPEG file."); if (file.size > 5 * 1024 * 1024) return setError("Files must be 5 MB or smaller."); setSaving(true); setError(null); try { const contentBase64 = await new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result).split(",")[1]); reader.onerror = reject; reader.readAsDataURL(file); }); await documents.upload({ contractorId: Number(contractorId), documentType: type, mimeType: file.type, originalFilename: file.name, contentBase64, expiryDate: expiryDate || null }); setFile(null); setExpiryDate(""); await load(contractorId); } catch (e) { setError(e.message); } finally { setSaving(false); } };
  const review = async (document, status) => { const rejectionReason = status === "REJECTED" ? window.prompt("Rejection reason") : null; if (status === "REJECTED" && !rejectionReason) return; try { await documents.review(document.id, { status, rejectionReason }); await load(contractorId); } catch (e) { setError(e.message); } };
  return <DashboardLayout title="Compliance"><div className="mx-auto flex max-w-4xl flex-col gap-5"><h1 className="text-xl font-semibold text-text">Contractor Compliance</h1><AlertBanner message={error} /><label className="max-w-sm text-sm font-medium">Contractor<select className="mt-1 w-full rounded-md border border-border p-2" value={contractorId} onChange={(e) => { setContractorId(e.target.value); load(e.target.value); }}>{contractors.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label>{loading ? <Spinner label="Loading compliance…" /> : <><section className="rounded-lg bg-surface p-4 shadow-panel"><p className="font-medium text-text">Status: {data?.compliance.status}</p><p className="text-sm text-muted">Missing or invalid: {data?.compliance.missing_document_types.join(", ") || "None"}</p></section><form onSubmit={upload} className="flex flex-wrap items-end gap-3 rounded-lg bg-surface p-4 shadow-panel"><label className="text-sm">Document type<select className="mt-1 block rounded-md border border-border p-2" value={type} onChange={(e) => setType(e.target.value)}>{types.map((v) => <option key={v}>{v}</option>)}</select></label><label className="text-sm">Expiry date (optional)<input className="mt-1 block rounded-md border border-border p-2" type="date" value={expiryDate} onChange={(e) => setExpiryDate(e.target.value)} /></label><label className="text-sm">File<input className="mt-1 block text-sm" type="file" accept="application/pdf,image/png,image/jpeg" onChange={(e) => setFile(e.target.files?.[0] || null)} /></label><PrimaryButton isLoading={saving} loadingText="Uploading…" fullWidth={false}>Upload document</PrimaryButton></form><section className="rounded-lg bg-surface p-4 shadow-panel"><h2 className="mb-3 font-medium text-text">Documents</h2>{!data?.documents.length ? <p className="text-sm text-muted">No documents uploaded.</p> : <div className="flex flex-col gap-3">{data.documents.map((doc) => <div key={doc.id} className="flex flex-wrap items-center justify-between gap-3 border-b border-border pb-3"><div><p className="font-medium">{doc.document_type} · {doc.status}</p><p className="text-sm text-muted">{doc.original_filename}{doc.expiry_date ? ` · expires ${String(doc.expiry_date).slice(0, 10)}` : ""}</p>{doc.rejection_reason && <p className="text-sm text-danger">{doc.rejection_reason}</p>}</div>{doc.status === "PENDING" && <div className="flex gap-2"><button type="button" className="rounded border px-3 py-1 text-sm" onClick={() => review(doc, "VERIFIED")}>Verify</button><button type="button" className="rounded border px-3 py-1 text-sm" onClick={() => review(doc, "REJECTED")}>Reject</button></div>}</div>)}</div>}</section></>}</div></DashboardLayout>;
}
